"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robotSettings_t(object):
    __slots__ = ["timestamp", "desiredSpeed", "positionFromGPS", "changeLane"]

    def __init__(self):
        self.timestamp = 0
        self.desiredSpeed = 0
        self.positionFromGPS = [ 0.0 for dim0 in range(3) ]
        self.changeLane = False

    def encode(self):
        buf = BytesIO()
        buf.write(robotSettings_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.desiredSpeed))
        buf.write(struct.pack('>3d', *self.positionFromGPS[:3]))
        buf.write(struct.pack(">b", self.changeLane))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robotSettings_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robotSettings_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robotSettings_t()
        self.timestamp, self.desiredSpeed = struct.unpack(">qi", buf.read(12))
        self.positionFromGPS = struct.unpack('>3d', buf.read(24))
        self.changeLane = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if robotSettings_t in parents: return 0
        tmphash = (0x2f6c5eb55b26a404) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robotSettings_t._packed_fingerprint is None:
            robotSettings_t._packed_fingerprint = struct.pack(">Q", robotSettings_t._get_hash_recursive([]))
        return robotSettings_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

