"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robotFeedback_t(object):
    __slots__ = ["timestamp", "speedCurrent", "positionEstimation", "laneRight"]

    def __init__(self):
        self.timestamp = 0
        self.speedCurrent = 0
        self.positionEstimation = [ 0.0 for dim0 in range(3) ]
        self.laneRight = False

    def encode(self):
        buf = BytesIO()
        buf.write(robotFeedback_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.speedCurrent))
        buf.write(struct.pack('>3d', *self.positionEstimation[:3]))
        buf.write(struct.pack(">b", self.laneRight))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robotFeedback_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robotFeedback_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robotFeedback_t()
        self.timestamp, self.speedCurrent = struct.unpack(">qi", buf.read(12))
        self.positionEstimation = struct.unpack('>3d', buf.read(24))
        self.laneRight = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if robotFeedback_t in parents: return 0
        tmphash = (0x420d853e4b0df0fd) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robotFeedback_t._packed_fingerprint is None:
            robotFeedback_t._packed_fingerprint = struct.pack(">Q", robotFeedback_t._get_hash_recursive([]))
        return robotFeedback_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

